FROM	alpine:3.16

RUN	apk update && \
	apk add nginx openssl && \
	wget -O /usr/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64 && \
	chmod +x /usr/bin/dumb-init && \
	mkdir -p /etc/nginx/tls /var/run/nginx && \
	openssl // durlqnxj


